- name: TODAY
  slug: today
  width: wide
  head-widgets:
    - $include: ../widgets/search.yml
    - $include: ../widgets/context.yml
  columns:
    - size: full
      widgets:
        - $include: ../widgets/intelligence-today.yml
        - $include: ../widgets/personal-desk.yml
        - $include: ../widgets/focus-board.yml
        - $include: ../widgets/today-discovery-link.yml
        - $include: ../widgets/today-guide.yml
    - size: small
      widgets:
        - $include: ../widgets/today-summary.yml
        - $include: ../widgets/market-pulse.yml
