- name: TODAY
  slug: today
  width: default
  head-widgets:
    - $include: ../widgets/search.yml
    - $include: ../widgets/context.yml
  columns:
    - size: small
      widgets:
        - $include: ../widgets/market-pulse.yml
    - size: full
      widgets:
        - $include: ../widgets/today-summary.yml
        - $include: ../widgets/today-guide.yml
