- type: rss
  title: Community widget commits
  title-url: https://github.com/glanceapp/community-widgets
  cache: 6h
  limit: 3
  collapse-after: 3
  single-line-titles: true
  feeds:
    - url: https://github.com/glanceapp/community-widgets/commits/main.atom
      title: Community widgets
      limit: 3
