- type: rss
  title: Reddit · r/selfhosted
  title-url: https://www.reddit.com/r/selfhosted/
  cache: 1h
  limit: 4
  collapse-after: 3
  single-line-titles: true
  feeds:
    - url: https://www.reddit.com/r/selfhosted/.rss
      title: r/selfhosted
      limit: 4
